NIFTY_TICKERS = [
"RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS",
"KOTAKBANK.NS","LT.NS","SBIN.NS","ITC.NS","BHARTIARTL.NS",
"ASIANPAINT.NS","AXISBANK.NS","BAJFINANCE.NS","MARUTI.NS",
"HCLTECH.NS","WIPRO.NS","SUNPHARMA.NS","ULTRACEMCO.NS",
"TITAN.NS","NESTLEIND.NS"
]

SECTOR_MAP = {
"IT":["TCS.NS","INFY.NS","HCLTECH.NS","WIPRO.NS"],
"BANKING":["HDFCBANK.NS","ICICIBANK.NS","SBIN.NS","AXISBANK.NS"],
"FMCG":["ITC.NS","NESTLEIND.NS"],
"AUTO":["MARUTI.NS"],
"ENERGY":["RELIANCE.NS"]
}